name: ao
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  curved_carousel: ^0.0.8
  gemini_ai_chat: ^0.0.5
  gemini_flutter: ^0.1.1
  http: ^1.2.2
 
  
dev_dependencies: 

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  flutter_launcher_icons: "^0.14.1"
  
  



flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

