name: ao
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2
  
  


dependencies:
 
  flutter:
    sdk: flutter
  curved_carousel: ^0.0.8
  
  http: ^1.2.2
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.2.1


  
 
  
dev_dependencies: 

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  flutter_launcher_icons: "^0.14.1"
  
  



flutter:

  uses-material-design: true
  assets: 
    - .env
    - assets/images/
    - assets/icons/
 
  
